<a href="https://colab.research.google.com/github/zainikhan999/Zainab_Khan_Ai_Collab_Notebooks_CS6/blob/main/LabTask5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This file has both the lab work and lab tasks



In [ ]:
num=95;
if (num%2==0):
  print("num is even")
else :
  print("num is odd")

num is odd


In [ ]:
# 1.	Write a program that calculates the sum of all even numbers from 1 to 20 using a for loop.
sum = 0
for i in range(1, 21):
    if i % 2 == 0:
        sum = sum + i
print("The sum of all even numbers from 1 to 20 is:", sum)

The sum of all even numbers from 1 to 20 is: 110


In [ ]:
# 3.	Extend the first list with elements from the second list.
list1=[9,35,343]
list2=[45,4545,323]
list1.extend(list2)


# Numpy array

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
print(arr[1])

2


In [ ]:
list=[1,2,3,4,5]
arr=np.array(list)
print(arr)

[1 2 3 4 5]


In [ ]:
# range from 1-10, last will be ommitted
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
app=np.array([1,2,3,4,5],dtype=float)
print(app)
print(app.dtype)

[1. 2. 3. 4. 5.]
float64


In [ ]:
app=np.array([1,2,3,4,5],dtype=float)
# print(app)
print(app.dtype)
# astypes convert orignal to bool , dtype is attribute
print(app.astype(bool))


float64
[ True  True  True  True  True]


# Arrays

In [ ]:
# 0-d array
print(np.array(42))

42


In [ ]:
# 1-d array
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
# 2-d
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0][1])

[[1 2 3]
 [4 5 6]]
2


In [ ]:
# 3-d
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(arr[0][1])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[4 5 6]


In [ ]:
# arange
a=np.arange(1,7).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3d arrays
# depth ,rows , columns
a=np.arange(1,13).reshape(2,2,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)



0
1
2
3
()
(5,)
(2, 3)
(2, 2, 3)


# Matrix

In [ ]:
# matrix is always 2d
a=np.matrix([1,2,3,4,5])
print(a)

[[1 2 3 4 5]]


In [ ]:
# dot product
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
print(np.dot(a,b))

55


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
print(a*b)

[ 1  4  9 16 25]


In [ ]:
# 2d array dot product
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[1,2,3],[4,5,6]])
# dot product number or columns of 1st row should be equal to rows of second
print(np.dot(a,b))
print(np.dot(a,c.T))

[[30 36 42]
 [66 81 96]]
[[14 32]
 [32 77]]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
# row ka phla index aur column ka phla, : ka mtlb hy k
print(b[:,1])
print(b[0,-1])
print(b[0][-1])

[2 5]
3
3


In [ ]:
# copy()
a=np.array([1,2,3,4,5])
x=a.view()
b=a.copy()
a[0]=100
print(a)
print(b)
print(x)

[100   2   3   4   5]
[1 2 3 4 5]
[100   2   3   4   5]


In [ ]:
a=np.array([4,5,6,4])
a[0]=9
print(a)

[9 5 6 4]


In [ ]:
# 2d array k index ke vaue chnage nho ho skhti
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# 0=rows , 1=column
b=np.insert(a,2,99,axis=0)
print(a)
print(b)
a[0]=100
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [99 99 99 99 99]]
[[100 100 100 100 100]
 [  6   7   8   9  10]]


In [ ]:
# concatenate
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.concatenate((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# prompt: conactenate 2d array

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Concatenate along rows (axis=0)
c = np.concatenate((a, b), axis=0)
print("Concatenated along rows:")
print(c)

# Concatenate along columns (axis=1)
d = np.concatenate((a, b), axis=1)
print("\nConcatenated along columns:")
print(d)


Concatenated along rows:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along columns:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# linspace , by default 50
arr=np.linspace(0,10)
print(arr)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [ ]:
# linspace , num=5
arr=np.linspace(0,2,num=5)
print(arr)

[0.  0.5 1.  1.5 2. ]


In [ ]:
# ignore last value
arr=np.linspace(0,2,num=5,endpoint=False, dtype=float)
print(arr)

[0.  0.4 0.8 1.2 1.6]


In [ ]:
import numpy as np
a=np.random.random()
arr=np.random.random((4,3))
print(arr)
print(a)

[[0.68298458 0.06586756 0.40164674]
 [0.80140189 0.91693282 0.07493165]
 [0.19871305 0.14167756 0.0635511 ]
 [0.32684103 0.88749555 0.11069461]]
0.4500980887699896


# **Lab Task 5**

In [ ]:
# Task 1: Consider 2-d array and Convert all the elements of a num py array from float to Bool datatype.
app=np.array([[2.5,3.6,4.3,5.1],[4.2,5.5,6.1,3.1]], dtype="bool")
print(app)


[[ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
# Task2: Write a Python program that uses insert function to add an element to a specific position in a array.
# •	add the element 55 at position 2.
# •	Print the updated array after the insertion.

arr=np.array([3,4,5,6,6])
arr2=np.insert(arr,1,55)
print(arr2)


[ 3 55  4  5  6  6]


In [ ]:
# Task3: Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4
arr=np.arange(0,101,2)
print(arr)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
# Task 4:Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)
matrix1=np.array([1,3,4,5])
matrix2=np.array([5,9,8,9])
print(matrix1*matrix2)

[ 5 27 32 45]


In [ ]:
#Task5: Consider a 1-d array and check whether the specific number is present or not?
arr5=np.array([3,5,63,7,8])
user=int(input("enter number"))
# initialize the variable with false
check=False
for x in arr5:
  if(user==x):
    check=True

if (check==True):
    print("found")
else:
  print("not found")






enter number7
found
